"""Comprehensive tests for the Go Kubernetes Developer Agent.

This module tests the Development Agent's ability to generate production-quality
Go code for Kubernetes/OpenShift features based on design analysis and implementation plans.

Tests verify the agent generates code with:
- Security standards (TLS 1.3, no hardcoded secrets)
- Comprehensive Go doc comments
- Table-driven unit tests
- PR description with "Generated by AI" footer
"""

import os
import pytest
from unittest.mock import Mock, patch

from agents.go_k8s_developer import (
    run_development,
    DevelopmentAgentError,
    _validate_context,
    _build_development_prompt,
    _parse_development_output,
    _split_into_sections,
    _extract_code_files,
    _extract_file_path,
    _extract_first_code_block,
    _extract_bullet_points,
    generate_file_summary,
)


# Sample test data
SAMPLE_CONTEXT = {
    "issue_title": "Add timeout support to BuildRun API",
    "implementation_plan": """
1. Update BuildRun API types with timeout field
2. Add validation webhook logic for timeout values
3. Implement timeout monitoring in controller reconciliation loop
4. Add comprehensive unit and integration tests
5. Update API documentation and examples
""",
    "design_analysis": """
# Design Analysis: Add Timeout Support to BuildRun API

## Problem Statement
Users cannot specify build timeouts, leading to hung builds consuming cluster resources.

## Impacted Components
- buildrun_api: Add timeout field to BuildRun spec
- buildrun_controller: Implement timeout enforcement logic
- webhook_validation: Add validation for timeout values

## Risks
- Breaking change if not implemented with backward compatibility
- Timeout granularity needs careful consideration

## Acceptance Criteria
- BuildRun spec accepts timeout field
- Controller terminates builds exceeding timeout
- Backward compatible with existing BuildRuns
""",
    "impacted_components": ["buildrun_api", "buildrun_controller", "webhook_validation"],
    "acceptance_criteria": [
        "BuildRun spec accepts timeout field",
        "Controller terminates builds exceeding timeout",
        "Backward compatible with existing BuildRuns",
    ],
    "risks": ["Breaking change risk", "Timeout granularity considerations"],
    "issue_type": "feature",
    "issue_description": "Users need to specify build timeout to prevent hanging builds",
    "session_id": "test-session-123",
}

SAMPLE_DEVELOPMENT_OUTPUT = """
## Code Files

### pkg/apis/build/v1beta1/buildrun_types.go

This file adds the Timeout field to the BuildRun spec.

```go
package v1beta1

import (
    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BuildRunSpec defines the desired state of BuildRun
type BuildRunSpec struct {
    // Timeout defines the maximum amount of time the BuildRun should run.
    // The timeout is measured from the time the BuildRun is created.
    // If not specified, the BuildRun will run indefinitely.
    // +optional
    Timeout *metav1.Duration `json:"timeout,omitempty"`
}
```

### pkg/controller/buildrun/timeout.go

Implements timeout enforcement in the controller.

```go
package buildrun

import (
    "context"
    "fmt"
    "time"

    shipwright "github.com/shipwright-io/build/pkg/apis/build/v1beta1"
)

// CheckTimeout verifies if the BuildRun has exceeded its timeout.
// Returns true if timeout is exceeded, false otherwise.
func CheckTimeout(ctx context.Context, br *shipwright.BuildRun) (bool, error) {
    if br.Spec.Timeout == nil {
        return false, nil
    }

    if br.Status.StartTime == nil {
        return false, nil
    }

    elapsed := time.Since(br.Status.StartTime.Time)
    if elapsed > br.Spec.Timeout.Duration {
        return true, fmt.Errorf("build timeout exceeded: %v > %v", elapsed, br.Spec.Timeout.Duration)
    }

    return false, nil
}
```

## Test Files

### pkg/apis/build/v1beta1/buildrun_types_test.go

```go
package v1beta1

import (
    "testing"
    "time"

    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

func TestBuildRunSpec_Timeout(t *testing.T) {
    tests := []struct {
        name    string
        timeout *metav1.Duration
        want    bool
    }{
        {
            name:    "with timeout",
            timeout: &metav1.Duration{Duration: 30 * time.Minute},
            want:    true,
        },
        {
            name:    "without timeout",
            timeout: nil,
            want:    false,
        },
    }

    for _, tt := range tests {
        t.Run(tt.name, func(t *testing.T) {
            spec := BuildRunSpec{
                Timeout: tt.timeout,
            }
            got := spec.Timeout != nil
            if got != tt.want {
                t.Errorf("BuildRunSpec.Timeout = %v, want %v", got, tt.want)
            }
        })
    }
}
```

### pkg/controller/buildrun/timeout_test.go

```go
package buildrun

import (
    "context"
    "testing"
    "time"

    metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

    shipwright "github.com/shipwright-io/build/pkg/apis/build/v1beta1"
)

func TestCheckTimeout(t *testing.T) {
    now := metav1.Now()
    pastTime := metav1.NewTime(now.Add(-1 * time.Hour))

    tests := []struct {
        name        string
        buildRun    *shipwright.BuildRun
        wantTimeout bool
        wantErr     bool
    }{
        {
            name: "no timeout specified",
            buildRun: &shipwright.BuildRun{
                Spec: shipwright.BuildRunSpec{
                    Timeout: nil,
                },
                Status: shipwright.BuildRunStatus{
                    StartTime: &now,
                },
            },
            wantTimeout: false,
            wantErr:     false,
        },
        {
            name: "timeout exceeded",
            buildRun: &shipwright.BuildRun{
                Spec: shipwright.BuildRunSpec{
                    Timeout: &metav1.Duration{Duration: 30 * time.Minute},
                },
                Status: shipwright.BuildRunStatus{
                    StartTime: &pastTime,
                },
            },
            wantTimeout: true,
            wantErr:     true,
        },
        {
            name: "timeout not exceeded",
            buildRun: &shipwright.BuildRun{
                Spec: shipwright.BuildRunSpec{
                    Timeout: &metav1.Duration{Duration: 2 * time.Hour},
                },
                Status: shipwright.BuildRunStatus{
                    StartTime: &pastTime,
                },
            },
            wantTimeout: false,
            wantErr:     false,
        },
    }

    for _, tt := range tests {
        t.Run(tt.name, func(t *testing.T) {
            ctx := context.Background()
            gotTimeout, err := CheckTimeout(ctx, tt.buildRun)

            if (err != nil) != tt.wantErr {
                t.Errorf("CheckTimeout() error = %v, wantErr %v", err, tt.wantErr)
                return
            }

            if gotTimeout != tt.wantTimeout {
                t.Errorf("CheckTimeout() = %v, want %v", gotTimeout, tt.wantTimeout)
            }
        })
    }
}
```

## PR Description

Add BuildRun timeout support to prevent hung builds from consuming cluster resources indefinitely.

This PR introduces a configurable timeout field to the BuildRun API, allowing users to specify
maximum execution time for builds. The controller enforces timeouts and properly cleans up
resources when exceeded.

### Changes Made

- Added `Timeout` field to BuildRun spec (optional, backward compatible)
- Implemented timeout checking logic in controller
- Added comprehensive unit tests with table-driven structure
- All tests include proper error handling and edge cases

### Security Considerations

- **TLS Configuration**: N/A for this change (API schema only)
- **Secret Handling**: No secrets involved in timeout implementation
- **Input Validation**: Timeout values validated via webhook (separate PR)
- **Logging Safety**: No sensitive data logged during timeout checks

### Testing Performed

- Unit tests covering timeout field presence/absence
- Unit tests for timeout enforcement logic (exceeded, not exceeded, no timeout)
- All tests use table-driven structure for comprehensive coverage
- Edge cases tested: nil timeout, nil start time, various durations

### Dependencies

No new dependencies added. Uses existing k8s.io/apimachinery/pkg/apis/meta/v1 package.

---
Generated by AI

## Security Notes

- TLS 1.3: Not applicable to this API schema change
- No hardcoded secrets: No credentials or sensitive data in implementation
- Input validation: Timeout field validation handled by admission webhook
- Safe logging: Timeout duration logged but contains no sensitive information
- Backward compatibility: Optional field ensures existing BuildRuns unaffected

## Dependencies

- k8s.io/apimachinery/pkg/apis/meta/v1 (already in use)

No new external dependencies required for this feature.

## Next Steps

- Implement admission webhook validation for timeout field
- Add integration tests with actual BuildRun execution
- Update BuildRun controller reconciliation loop to call CheckTimeout
- Update API documentation with timeout field examples
- Add e2e tests for complete timeout scenario
- Configure RBAC permissions if controller needs additional access
"""


class TestDevelopmentAgent:
    """Test suite for Development Agent functionality."""

    def test_development_agent_structure(self):
        """Test that development agent function exists and is callable."""
        assert callable(run_development)

    def test_development_agent_missing_required_fields(self):
        """Test that development agent validates required context fields."""
        # Missing issue_title
        with pytest.raises(DevelopmentAgentError, match="Missing required context fields"):
            run_development({
                "implementation_plan": "Some plan",
                "design_analysis": "Some analysis",
            })

        # Missing implementation_plan
        with pytest.raises(DevelopmentAgentError, match="Missing required context fields"):
            run_development({
                "issue_title": "Add feature",
                "design_analysis": "Some analysis",
            })

        # Missing design_analysis
        with pytest.raises(DevelopmentAgentError, match="Missing required context fields"):
            run_development({
                "issue_title": "Add feature",
                "implementation_plan": "Some plan",
            })

    def test_development_agent_invalid_field_types(self):
        """Test validation of context field types."""
        # issue_title not a string
        with pytest.raises(ValueError, match="must be a non-empty string"):
            _validate_context({
                "issue_title": "",
                "implementation_plan": "Plan",
                "design_analysis": "Analysis",
            })

        # impacted_components not a list
        with pytest.raises(ValueError, match="must be a list"):
            _validate_context({
                "issue_title": "Title",
                "implementation_plan": "Plan",
                "design_analysis": "Analysis",
                "impacted_components": "not_a_list",
            })

        # acceptance_criteria not a list
        with pytest.raises(ValueError, match="must be a list"):
            _validate_context({
                "issue_title": "Title",
                "implementation_plan": "Plan",
                "design_analysis": "Analysis",
                "acceptance_criteria": "not_a_list",
            })

    def test_development_agent_missing_api_key(self):
        """Test that development agent fails gracefully without API key."""
        with patch.dict(os.environ, {}, clear=True):
            with pytest.raises(DevelopmentAgentError, match="Failed to initialize"):
                run_development(SAMPLE_CONTEXT)

    @pytest.mark.skipif(
        not bool(os.getenv("ANTHROPIC_API_KEY")),
        reason="ANTHROPIC_API_KEY not set - using mock instead"
    )
    def test_development_agent_with_real_api(self):
        """Test development agent with real Claude API (if key available)."""
        result = run_development(SAMPLE_CONTEXT)

        # Validate output structure
        assert "code_files" in result
        assert "test_files" in result
        assert "pr_description" in result
        assert "security_notes" in result
        assert "dependencies" in result
        assert "next_steps" in result

        # Validate content types
        assert isinstance(result["code_files"], list)
        assert isinstance(result["test_files"], list)
        assert isinstance(result["pr_description"], str)
        assert isinstance(result["security_notes"], list)
        assert isinstance(result["dependencies"], list)
        assert isinstance(result["next_steps"], list)

        # Validate PR description ends with "Generated by AI"
        assert "Generated by AI" in result["pr_description"]

        # Should generate some files
        assert len(result["code_files"]) > 0 or len(result["test_files"]) > 0

        # Print for manual inspection
        print("\n" + "="*80)
        print("CODE GENERATION OUTPUT (Real API)")
        print("="*80)
        print(f"\nCode Files: {len(result['code_files'])}")
        print(f"Test Files: {len(result['test_files'])}")
        print(f"\nPR Description:\n{result['pr_description'][:300]}...")
        print(f"\nSecurity Notes: {result['security_notes']}")
        print(f"\nDependencies: {result['dependencies']}")

    @pytest.mark.skipif(
        bool(os.getenv("ANTHROPIC_API_KEY")),
        reason="ANTHROPIC_API_KEY is set - skipping mock test"
    )
    def test_development_agent_with_mock(self):
        """Test development agent with mocked Claude API."""
        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                result = run_development(SAMPLE_CONTEXT)

                # Validate mock was called
                mock_client.messages.create.assert_called_once()
                call_args = mock_client.messages.create.call_args

                # Validate request structure
                assert call_args.kwargs["model"] == "claude-sonnet-4-20250514"
                assert call_args.kwargs["max_tokens"] == 16000
                assert call_args.kwargs["temperature"] == 0.2
                assert len(call_args.kwargs["messages"]) == 1

                # Validate output
                assert len(result["code_files"]) > 0
                assert len(result["test_files"]) > 0
                assert "Generated by AI" in result["pr_description"]

    def test_development_output_schema(self):
        """Test that output contains all required fields with correct types."""
        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                result = run_development(SAMPLE_CONTEXT)

                # Verify all required fields exist
                required_fields = [
                    "code_files",
                    "test_files",
                    "pr_description",
                    "security_notes",
                    "dependencies",
                    "next_steps",
                ]
                for field in required_fields:
                    assert field in result, f"Missing field: {field}"

                # Verify field types
                assert isinstance(result["code_files"], list)
                assert isinstance(result["test_files"], list)
                assert isinstance(result["pr_description"], str)
                assert isinstance(result["security_notes"], list)
                assert isinstance(result["dependencies"], list)
                assert isinstance(result["next_steps"], list)

    def test_development_pr_description_footer(self):
        """Test that PR description ends with 'Generated by AI' footer."""
        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                result = run_development(SAMPLE_CONTEXT)

                # Verify footer is present
                assert "Generated by AI" in result["pr_description"]
                # Verify it's near the end
                assert result["pr_description"].strip().endswith("Generated by AI")

    def test_development_code_file_structure(self):
        """Test that code_files have required fields (path, content, description)."""
        parsed = _parse_development_output(SAMPLE_DEVELOPMENT_OUTPUT)

        assert len(parsed["code_files"]) > 0, "Should extract code files"

        for file_info in parsed["code_files"]:
            # Each file should have path, content, and description
            assert "path" in file_info
            assert "content" in file_info
            assert "description" in file_info

            # Validate types
            assert isinstance(file_info["path"], str)
            assert isinstance(file_info["content"], str)
            assert isinstance(file_info["description"], str)

            # Path should end with .go
            assert file_info["path"].endswith(".go"), f"Invalid path: {file_info['path']}"

            # Content should not be empty
            assert len(file_info["content"]) > 0, f"Empty content for {file_info['path']}"

    def test_development_test_file_structure(self):
        """Test that test_files have required fields (path, content)."""
        parsed = _parse_development_output(SAMPLE_DEVELOPMENT_OUTPUT)

        assert len(parsed["test_files"]) > 0, "Should extract test files"

        for file_info in parsed["test_files"]:
            # Each test file should have path and content
            assert "path" in file_info
            assert "content" in file_info

            # Validate types
            assert isinstance(file_info["path"], str)
            assert isinstance(file_info["content"], str)

            # Path should end with _test.go
            assert file_info["path"].endswith("_test.go"), f"Invalid test path: {file_info['path']}"

            # Content should contain test functions
            assert "func Test" in file_info["content"], f"No test functions in {file_info['path']}"

    def test_development_security_validation(self):
        """Test that security notes are generated."""
        parsed = _parse_development_output(SAMPLE_DEVELOPMENT_OUTPUT)

        # Should have security notes
        assert "security_notes" in parsed
        assert isinstance(parsed["security_notes"], list)

        # Should have at least some security considerations
        # (may be empty if not applicable, but field should exist)
        security_notes = parsed["security_notes"]
        assert isinstance(security_notes, list)

    def test_development_with_repo_path(self):
        """Test development agent with repository path for context."""
        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                result = run_development(SAMPLE_CONTEXT, repo_path="/fake/repo/path")

                # Should still generate valid output
                assert "code_files" in result
                assert "test_files" in result

                # Check that repo_path was included in prompt
                call_args = mock_client.messages.create.call_args
                user_prompt = call_args.kwargs["messages"][0]["content"]
                assert "/fake/repo/path" in user_prompt


class TestHelperFunctions:
    """Test suite for development agent helper functions."""

    def test_validate_context_success(self):
        """Test context validation with valid input."""
        # Should not raise exception
        _validate_context(SAMPLE_CONTEXT)

    def test_build_development_prompt(self):
        """Test development prompt construction."""
        prompt = _build_development_prompt(SAMPLE_CONTEXT)

        # Should contain all major sections
        assert "Code Generation Request" in prompt
        assert SAMPLE_CONTEXT["issue_title"] in prompt
        assert SAMPLE_CONTEXT["design_analysis"] in prompt
        assert SAMPLE_CONTEXT["implementation_plan"] in prompt
        assert "Impacted Components" in prompt
        assert "Acceptance Criteria" in prompt
        assert "Risks to Address" in prompt

        # Should contain code generation instructions
        assert "Go Code Files" in prompt
        assert "Security Requirements" in prompt
        assert "TLS 1.3" in prompt
        assert "No Hardcoded Secrets" in prompt
        assert "Unit Tests" in prompt
        assert "Table-driven test structure" in prompt
        assert "PR Description" in prompt
        assert "Generated by AI" in prompt

    def test_build_development_prompt_minimal(self):
        """Test development prompt with minimal required fields."""
        minimal_context = {
            "issue_title": "Simple feature",
            "implementation_plan": "Basic plan",
            "design_analysis": "Basic analysis",
        }

        prompt = _build_development_prompt(minimal_context)

        # Should still produce valid prompt
        assert "Code Generation Request" in prompt
        assert "Simple feature" in prompt
        assert "Basic plan" in prompt
        assert "Basic analysis" in prompt

    def test_split_into_sections(self):
        """Test splitting output into sections."""
        sections = _split_into_sections(SAMPLE_DEVELOPMENT_OUTPUT)

        # Should extract all major sections
        assert "code files" in sections
        assert "test files" in sections
        assert "pr description" in sections
        assert "security notes" in sections
        assert "dependencies" in sections
        assert "next steps" in sections

    def test_extract_code_files(self):
        """Test extraction of code files from section."""
        sections = _split_into_sections(SAMPLE_DEVELOPMENT_OUTPUT)
        code_section = sections.get("code files", "")

        files = _extract_code_files(code_section)

        # Should extract multiple files
        assert len(files) > 0

        # Check first file structure
        first_file = files[0]
        assert "path" in first_file
        assert "content" in first_file
        assert "description" in first_file

        # Verify actual content
        paths = [f["path"] for f in files]
        assert any("buildrun_types.go" in p for p in paths)

    def test_extract_file_path(self):
        """Test file path extraction from various formats."""
        # Format 1: Plain path
        assert "pkg/apis/build.go" in _extract_file_path("pkg/apis/build.go")

        # Format 2: With "File:" prefix
        assert "pkg/controller/buildrun.go" in _extract_file_path("File: pkg/controller/buildrun.go")

        # Format 3: With markdown
        assert "pkg/util/validation.go" in _extract_file_path("### pkg/util/validation.go")

        # Format 4: With backticks
        assert "pkg/webhook/validation.go" in _extract_file_path("`pkg/webhook/validation.go`")

    def test_extract_first_code_block(self):
        """Test extraction of first code block."""
        text = """
Some text before

```go
package main

func main() {
    fmt.Println("Hello")
}
```

Some text after
"""
        code = _extract_first_code_block(text, "go")
        assert "package main" in code
        assert "func main" in code

    def test_extract_bullet_points(self):
        """Test extraction of bullet points."""
        text = """
Some intro text

- First item
- Second item
* Third item with asterisk
• Fourth item with bullet

Some conclusion
"""
        items = _extract_bullet_points(text)

        assert len(items) == 4
        assert "First item" in items
        assert "Second item" in items
        assert "Third item with asterisk" in items
        assert "Fourth item with bullet" in items

    def test_parse_development_output(self):
        """Test parsing of complete development output."""
        result = _parse_development_output(SAMPLE_DEVELOPMENT_OUTPUT)

        # Validate structure
        assert "code_files" in result
        assert "test_files" in result
        assert "pr_description" in result
        assert "security_notes" in result
        assert "dependencies" in result
        assert "next_steps" in result

        # Validate content extraction
        assert len(result["code_files"]) > 0
        assert len(result["test_files"]) > 0
        assert "Generated by AI" in result["pr_description"]
        assert len(result["security_notes"]) > 0

    def test_generate_file_summary(self):
        """Test file summary generation."""
        dev_results = {
            "code_files": [
                {"path": "pkg/apis/build.go", "content": "code", "description": "API types"},
                {"path": "pkg/controller/buildrun.go", "content": "code", "description": "Controller"},
            ],
            "test_files": [
                {"path": "pkg/apis/build_test.go", "content": "test code"},
            ],
            "security_notes": ["TLS 1.3 configured", "No hardcoded secrets"],
            "dependencies": ["k8s.io/client-go"],
            "next_steps": ["Add integration tests", "Update documentation"],
        }

        summary = generate_file_summary(dev_results)

        assert "Code Generation Summary" in summary
        assert "2" in summary  # Code files count
        assert "1" in summary  # Test files count
        assert "pkg/apis/build.go" in summary
        assert "pkg/controller/buildrun.go" in summary
        assert "pkg/apis/build_test.go" in summary
        assert "TLS 1.3" in summary
        assert "k8s.io/client-go" in summary
        assert "Add integration tests" in summary


class TestEdgeCases:
    """Test edge cases and error handling."""

    def test_empty_implementation_plan(self):
        """Test with empty implementation plan."""
        context = SAMPLE_CONTEXT.copy()
        context["implementation_plan"] = ""

        with pytest.raises(ValueError, match="must be a non-empty string"):
            _validate_context(context)

    def test_anthropic_api_error(self):
        """Test handling of Anthropic API errors."""
        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.side_effect = Exception("API Error")
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                with pytest.raises(DevelopmentAgentError, match="Unexpected error"):
                    run_development(SAMPLE_CONTEXT)

    def test_invalid_anthropic_client_initialization(self):
        """Test handling of client initialization errors."""
        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_get_client.side_effect = Exception("Invalid API key")

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "invalid-key"}):
                with pytest.raises(DevelopmentAgentError, match="Failed to initialize"):
                    run_development(SAMPLE_CONTEXT)

    def test_malformed_response(self):
        """Test handling of malformed API response."""
        mock_response = Mock()
        mock_response.content = []  # Empty content

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                with pytest.raises((DevelopmentAgentError, IndexError)):
                    run_development(SAMPLE_CONTEXT)

    def test_output_without_pr_description(self):
        """Test parsing output without PR description section."""
        output_without_pr = """
## Code Files

### pkg/example.go

```go
package example

func Example() {}
```

## Test Files

### pkg/example_test.go

```go
package example

import "testing"

func TestExample(t *testing.T) {}
```
"""
        result = _parse_development_output(output_without_pr)

        # PR description should exist but may be empty or have default footer
        assert "pr_description" in result
        # Footer should be added automatically
        assert "Generated by AI" in result["pr_description"]

    def test_output_without_security_notes(self):
        """Test parsing output without security notes section."""
        output_minimal = """
## Code Files

### pkg/example.go

```go
package example
```

## PR Description

Simple change.
"""
        result = _parse_development_output(output_minimal)

        # Security notes should exist as empty list
        assert "security_notes" in result
        assert isinstance(result["security_notes"], list)

    def test_heartbeat_emission(self):
        """Test that heartbeats are emitted during execution."""
        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            with patch("agents.go_k8s_developer.emit_heartbeat") as mock_heartbeat:
                mock_client = Mock()
                mock_client.messages.create.return_value = mock_response
                mock_get_client.return_value = mock_client

                with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                    run_development(SAMPLE_CONTEXT)

                    # Should emit at least 2 heartbeats (start and complete)
                    assert mock_heartbeat.call_count >= 2

                    # Verify heartbeat calls
                    calls = mock_heartbeat.call_args_list
                    assert calls[0][0][0] == "development"
                    assert "development_start" in str(calls[0])
                    assert "development_complete" in str(calls[-1])


class TestIntegration:
    """Integration tests for development agent."""

    def test_full_context_flow(self):
        """Test with full context from design phase."""
        full_context = {
            "issue_title": "Add BuildRun timeout support",
            "issue_description": "Comprehensive description of the timeout feature",
            "issue_type": "feature",
            "implementation_plan": "Detailed step-by-step implementation plan",
            "design_analysis": "Complete design analysis with architecture details",
            "impacted_components": ["buildrun_api", "buildrun_controller", "webhook"],
            "acceptance_criteria": ["Timeout enforced", "Backward compatible", "Well tested"],
            "risks": ["Breaking changes", "Performance impact", "Edge cases"],
            "session_id": "integration-test-session",
        }

        mock_response = Mock()
        mock_response.content = [Mock(text=SAMPLE_DEVELOPMENT_OUTPUT)]

        with patch("agents.go_k8s_developer.get_anthropic_client") as mock_get_client:
            mock_client = Mock()
            mock_client.messages.create.return_value = mock_response
            mock_get_client.return_value = mock_client

            with patch.dict(os.environ, {"ANTHROPIC_API_KEY": "test-key"}):
                result = run_development(full_context)

                # Validate comprehensive output
                assert all(key in result for key in [
                    "code_files", "test_files", "pr_description",
                    "security_notes", "dependencies", "next_steps"
                ])

                # Context should include all sections
                call_args = mock_client.messages.create.call_args
                user_prompt = call_args.kwargs["messages"][0]["content"]
                assert "Design Analysis" in user_prompt
                assert "Implementation Plan" in user_prompt
                assert "Impacted Components" in user_prompt
                assert "Acceptance Criteria" in user_prompt
                assert "Risks to Address" in user_prompt

                # Verify all components mentioned
                for component in full_context["impacted_components"]:
                    assert component in user_prompt


@pytest.fixture
def minimal_context():
    """Fixture providing minimal valid context."""
    return {
        "issue_title": "Simple feature",
        "implementation_plan": "Basic implementation steps",
        "design_analysis": "Basic design analysis",
    }


def test_required_context_validation(minimal_context):
    """Test that required context keys are validated."""
    # Remove required key
    incomplete = minimal_context.copy()
    del incomplete["implementation_plan"]

    with pytest.raises(DevelopmentAgentError, match="implementation_plan"):
        run_development(incomplete)


if __name__ == "__main__":
    # Run tests with verbose output
    pytest.main([__file__, "-v", "-s"])
