"""Go Kubernetes/OpenShift Developer Agent.

This module implements the Development Agent which generates production-quality
Go code for Kubernetes/OpenShift features based on design analysis and implementation plans.

The agent analyzes design documents and produces secure, maintainable Go code following
Kubernetes/OpenShift engineering standards, including comprehensive unit tests, Go doc
comments, and PR descriptions.
"""

import json
import os
import re
from typing import Any, Dict, List, Optional

try:
    from anthropic import APIError
except ImportError:
    raise ImportError(
        "anthropic library is required. Install with: uv pip install anthropic"
    )

from config.agent_prompts import DEVELOPMENT_AGENT_PROMPT
from config.auth_config import get_anthropic_client
from dashboard.heartbeat import emit_heartbeat
from tools.prompt_guard import sanitize_external_input
from utils.file_logger import get_logger, get_session_logger

# Initialize logger
logger = get_logger(__name__)


class DevelopmentAgentError(Exception):
    """Base exception for Development Agent errors."""


def run_development(
    context: Dict[str, Any],
    repo_path: Optional[str] = None
) -> Dict[str, Any]:
    """Generate production-quality Go code for Kubernetes/OpenShift features.

    This function analyzes design documents and implementation plans to generate
    secure, maintainable Go code with comprehensive tests and documentation.

    Args:
        context: Dictionary containing:
            - issue_title: str - Feature/bug title (required)
            - implementation_plan: list[str] - List of implementation steps from design agent (required)
            - design_analysis: str - Design document (required)
            - impacted_components: list - Components affected (optional)
            - acceptance_criteria: list - Acceptance criteria (optional)
            - risks: list - Identified risks (optional)
            - issue_type: str - Type of issue (bug/feature/refactor) (optional)
            - issue_description: str - Detailed description (optional)
            - session_id: str - Session identifier for heartbeats (optional)
        repo_path: Optional path to repository for context

    Returns:
        Dictionary containing:
            - code_files: List[dict] - Generated code files
                [{"path": str, "content": str, "description": str}]
            - test_files: List[dict] - Generated test files
                [{"path": str, "content": str}]
            - code_changes: Dict[str, str] - File paths mapped to change descriptions
            - files_modified: List[str] - All modified file paths (code + tests)
            - pr_description: str - Pull request description with "Generated by AI" footer
            - security_notes: List[str] - Security considerations
            - dependencies: List[str] - New dependencies added
            - next_steps: List[str] - Recommended next steps
            - raw_output: str - Raw LLM output for debugging

    Raises:
        DevelopmentAgentError: If required context is missing or generation fails
        ValueError: If required context fields are invalid

    Example:
        context = {
             "issue_title": "Add timeout support to BuildRun",
             "implementation_plan": "1. Add timeout field to BuildRun spec...",
             "design_analysis": "# Design for timeout feature...",
             "impacted_components": ["buildrun_api", "buildrun_controller"],
         }
        result = run_development(context)
        print(result["pr_description"])
    """
    # Get session-specific logger
    session_id = context.get("session_id", "unknown")
    session_logger = get_session_logger(session_id, "development_agent")

    logger.info(f"Starting development for session {session_id}: {context.get('issue_title', 'N/A')}")
    session_logger.info(f"Development agent started with context: {context.get('issue_title', 'N/A')}")

    # Validate required context
    try:
        _validate_context(context)
        logger.debug("Context validation passed")
    except (DevelopmentAgentError, ValueError) as e:
        logger.error(f"Context validation failed: {e}", exc_info=True)
        session_logger.error(f"Context validation failed: {e}")
        raise

    # Emit start heartbeat
    emit_heartbeat("development", {
        **context,
        "phase": "development_start"
    })

    # Get configured client (handles both API key and enterprise auth)
    try:
        client = get_anthropic_client()
        logger.info("Claude client initialized successfully")
        session_logger.info("Claude client initialized")
    except Exception as e:
        logger.error(f"Failed to initialize Claude client: {e}", exc_info=True)
        session_logger.error(f"Failed to initialize Claude client: {e}")
        raise DevelopmentAgentError(f"Failed to initialize Claude client: {e}") from e

    # Build the development prompt
    logger.debug("Building development prompt")
    user_prompt = _build_development_prompt(context, repo_path)
    session_logger.debug(f"Prompt length: {len(user_prompt)} chars")

    # Call Claude API
    try:
        model = os.getenv("CLAUDE_MODEL", "claude-sonnet-4-6")
        logger.info(f"Calling Claude API with model: {model}, max_tokens: 16000")
        session_logger.info(f"API Request: model={model}, max_tokens=16000, temperature=0.2")

        response = client.messages.create(
            model=model,
            max_tokens=16000,  # Large for code generation
            system=DEVELOPMENT_AGENT_PROMPT,
            messages=[
                {
                    "role": "user",
                    "content": user_prompt,
                }
            ],
            temperature=0.2,  # Lower temperature for more deterministic code
        )

        # Extract the development output from response
        dev_output = response.content[0].text
        logger.info(f"Received response from Claude API ({len(dev_output)} chars)")
        session_logger.info(f"Response length: {len(dev_output)} chars")

    except APIError as e:
        logger.error(f"Claude API call failed: {e}", exc_info=True)
        session_logger.error(f"Claude API call failed: {e}")
        raise DevelopmentAgentError(f"Claude API call failed: {e}") from e
    except Exception as e:
        logger.error(f"Unexpected error during code generation: {e}", exc_info=True)
        session_logger.error(f"Unexpected error: {e}")
        raise DevelopmentAgentError(f"Unexpected error during code generation: {e}") from e

    # Parse the structured output
    logger.debug("Parsing development output")
    parsed_result = _parse_development_output(dev_output)
    logger.info(f"Parsed {len(parsed_result.get('code_files', []))} code files and {len(parsed_result.get('test_files', []))} test files")
    session_logger.info(f"Generated {len(parsed_result.get('code_files', []))} code files, {len(parsed_result.get('test_files', []))} test files")

    # Synthesize code_changes and files_modified from code_files/test_files
    logger.debug("Synthesizing file tracking information")
    code_changes, files_modified = _synthesize_file_tracking(
        parsed_result.get("code_files", []),
        parsed_result.get("test_files", [])
    )
    session_logger.info(f"Tracked {len(files_modified)} modified files")

    # Emit completion heartbeat
    files_generated = len(parsed_result.get("code_files", [])) + len(parsed_result.get("test_files", []))
    emit_heartbeat("development", {
        **context,
        "phase": "development_complete",
        "files_generated": files_generated
    })

    logger.info(f"Development agent completed successfully. Generated {files_generated} files")
    session_logger.info(f"Development complete: {files_generated} files generated")

    return {
        "code_files": parsed_result.get("code_files", []),
        "test_files": parsed_result.get("test_files", []),
        "code_changes": code_changes,
        "files_modified": files_modified,
        "pr_description": parsed_result.get("pr_description", ""),
        "security_notes": parsed_result.get("security_notes", []),
        "dependencies": parsed_result.get("dependencies", []),
        "next_steps": parsed_result.get("next_steps", []),
        "raw_output": dev_output,  # Include raw output for debugging
    }


def _synthesize_file_tracking(code_files: List[dict], test_files: List[dict]) -> tuple:
    """Synthesize code_changes and files_modified from code_files and test_files.

    This function creates the state fields expected by graph.py from the structured
    file lists returned by the LLM.

    Args:
        code_files: List of code file dicts with path, content, description
        test_files: List of test file dicts with path, content

    Returns:
        Tuple of (code_changes dict, files_modified list)
    """
    code_changes = {}
    files_modified = []

    # Process code files
    for file_info in code_files:
        path = file_info.get("path", "")
        description = file_info.get("description", "Code implementation")
        if path:
            code_changes[path] = description
            files_modified.append(path)

    # Process test files
    for file_info in test_files:
        path = file_info.get("path", "")
        if path:
            code_changes[path] = "Test implementation"
            files_modified.append(path)

    return code_changes, files_modified


def _validate_context(context: Dict[str, Any]) -> None:
    """Validate that required context fields are present.

    Args:
        context: The context dictionary to validate

    Raises:
        DevelopmentAgentError: If required fields are missing
        ValueError: If field values are invalid
    """
    required_string_fields = ["issue_title", "design_analysis"]
    required_list_fields = ["implementation_plan"]

    # Check for missing fields
    all_required_fields = required_string_fields + required_list_fields
    missing_fields = [field for field in all_required_fields if field not in context]

    if missing_fields:
        raise DevelopmentAgentError(
            f"Missing required context fields: {', '.join(missing_fields)}. "
            f"Required fields are: {', '.join(all_required_fields)}"
        )

    # Validate non-empty strings
    for field in required_string_fields:
        if not isinstance(context[field], str) or not context[field].strip():
            raise ValueError(f"Field '{field}' must be a non-empty string")

    # Validate required list fields
    for field in required_list_fields:
        if not isinstance(context[field], list) or not context[field]:
            raise ValueError(f"Field '{field}' must be a non-empty list")

    # Validate optional list fields
    for field in ["impacted_components", "acceptance_criteria", "risks"]:
        if field in context and not isinstance(context[field], list):
            raise ValueError(f"Field '{field}' must be a list")


def _build_development_prompt(
    context: Dict[str, Any],
    repo_path: Optional[str] = None
) -> str:
    """Build the user prompt for code generation.

    Args:
        context: Context containing design analysis and implementation plan
        repo_path: Optional repository path for context

    Returns:
        Formatted prompt string
    """
    prompt_parts = [
        "# Code Generation Request\n",
        "## Feature/Bug Information\n",
    ]

    issue_title = sanitize_external_input(context.get("issue_title", ""), source="develop:issue_title")
    issue_description = sanitize_external_input(context.get("issue_description", ""), source="develop:issue_description")
    design_analysis = sanitize_external_input(context.get("design_analysis", ""), source="develop:design_analysis")
    acceptance_criteria = [
        sanitize_external_input(c, source=f"develop:acceptance_criteria:{i}")
        for i, c in enumerate(context.get("acceptance_criteria", []))
    ]
    risks = [
        sanitize_external_input(r, source=f"develop:risks:{i}")
        for i, r in enumerate(context.get("risks", []))
    ]
    impacted_components = [
        sanitize_external_input(c, source=f"develop:impacted_components:{i}")
        for i, c in enumerate(context.get("impacted_components", []))
    ]

    if issue_title:
        prompt_parts.append(f"**Title:** {issue_title}\n")

    if context.get("issue_type"):
        prompt_parts.append(f"**Type:** {context['issue_type']}\n")

    if issue_description:
        prompt_parts.append(f"\n**Description:**\n{issue_description}\n")

    prompt_parts.append("\n## Design Analysis\n")
    prompt_parts.append(f"{design_analysis}\n")

    # Convert implementation_plan list to formatted string
    implementation_plan = context.get("implementation_plan", [])
    if isinstance(implementation_plan, list):
        plan_text = "\n".join(f"{i+1}. {step}" for i, step in enumerate(implementation_plan))
    else:
        # Fallback for backward compatibility (if someone passes a string)
        plan_text = str(implementation_plan)

    prompt_parts.append("\n## Implementation Plan\n")
    prompt_parts.append(f"{plan_text}\n")

    if impacted_components:
        prompt_parts.append("\n## Impacted Components\n")
        for component in impacted_components:
            prompt_parts.append(f"- {component}\n")

    if acceptance_criteria:
        prompt_parts.append("\n## Acceptance Criteria\n")
        for idx, criterion in enumerate(acceptance_criteria, 1):
            prompt_parts.append(f"{idx}. {criterion}\n")

    if risks:
        prompt_parts.append("\n## Risks to Address\n")
        for risk in risks:
            prompt_parts.append(f"- {risk}\n")

    if repo_path:
        prompt_parts.append(f"\n## Repository Path\n")
        prompt_parts.append(f"{repo_path}\n")

    # Inject review feedback for auto-fix iterations
    review_feedback = _build_review_feedback_section(context)
    if review_feedback:
        prompt_parts.append(review_feedback)

    # Add code generation instructions
    prompt_parts.append(
        "\n## Code Generation Instructions\n\n"
        "Please generate production-quality Go code following these requirements:\n\n"
        "1. **Go Code Files**: Generate all necessary Go code files with:\n"
        "   - Full file paths relative to repository root\n"
        "   - Complete, compilable Go code\n"
        "   - Proper package declarations and imports\n"
        "   - Go doc comments for all exported types, functions, and methods\n"
        "   - Idiomatic Go patterns (error handling, context propagation)\n"
        "   - Kubernetes/OpenShift best practices (client-go, controller-runtime)\n\n"
        "2. **Security Requirements**:\n"
        "   - **TLS 1.3**: Use TLS 1.3 where TLS is configured\n"
        "   - **No Hardcoded Secrets**: Never hardcode credentials or sensitive data\n"
        "   - **Input Validation**: Validate all external inputs\n"
        "   - **Safe Logging**: Never log secrets or sensitive information\n"
        "   - **Secure Dependencies**: Use only well-maintained dependencies\n\n"
        "3. **Unit Tests**: Generate comprehensive unit tests with:\n"
        "   - Table-driven test structure\n"
        "   - Coverage of success, failure, and edge cases\n"
        "   - Proper mocking of external dependencies\n"
        "   - Clear test names and assertions\n"
        "   - Test file paths following Go conventions (*_test.go)\n\n"
        "4. **PR Description**: Generate a pull request description with:\n"
        "   - Summary of changes\n"
        "   - Rationale for the approach\n"
        "   - Security considerations (TLS, secrets, validation)\n"
        "   - Testing performed\n"
        "   - Dependencies added (if any)\n"
        "   - **MUST end with**: '---\\nGenerated by AI'\n\n"
        "5. **Dependencies**: List any new dependencies added to go.mod with:\n"
        "   - Package import path\n"
        "   - Version (if specific version required)\n"
        "   - Rationale for adding the dependency\n\n"
        "6. **Security Notes**: Document security considerations:\n"
        "   - TLS configuration approach\n"
        "   - Secret handling strategy\n"
        "   - Input validation details\n"
        "   - Any security-relevant changes\n\n"
        "7. **Next Steps**: Recommend follow-up actions:\n"
        "   - Integration testing needs\n"
        "   - Documentation updates required\n"
        "   - RBAC permissions to configure\n"
        "   - Deployment considerations\n\n"
        "**Important Guidelines:**\n"
        "- Follow existing project patterns and conventions\n"
        "- Use standard library when possible\n"
        "- Keep functions small and focused (single responsibility)\n"
        "- Use meaningful names that convey intent\n"
        "- Add context to all errors (fmt.Errorf with %w)\n"
        "- Pass context.Context through the entire call chain\n"
        "- Use defer for resource cleanup\n"
        "- Generate actual working Go code that compiles\n\n"
        "**Output Structure:**\n"
        "Please structure your output with clear section headers:\n"
        "- ## Code Files\n"
        "- ## Test Files\n"
        "- ## PR Description\n"
        "- ## Security Notes\n"
        "- ## Dependencies\n"
        "- ## Next Steps\n"
    )

    return "".join(prompt_parts)


def _parse_development_output(dev_output: str) -> Dict[str, Any]:
    """Parse structured information from the development output.

    Extracts code files, tests, PR description, and other artifacts from the LLM output.

    Args:
        dev_output: The complete development output in Markdown format

    Returns:
        Dictionary with extracted structured data
    """
    result = {
        "code_files": [],
        "test_files": [],
        "pr_description": "",
        "security_notes": [],
        "dependencies": [],
        "next_steps": [],
    }

    sections = _split_into_sections(dev_output)

    # Extract code files
    if "code files" in sections:
        result["code_files"] = _extract_code_files(sections["code files"])

    # Extract test files
    if "test files" in sections:
        result["test_files"] = _extract_code_files(sections["test files"])

    # Extract PR description — try multiple key variants
    pr_desc = (
        sections.get("pr description")
        or sections.get("pull request description")
        or sections.get("pr")
        or ""
    ).strip()
    # Ensure "Generated by AI" footer is present
    if not pr_desc.endswith("Generated by AI"):
        if pr_desc:
            pr_desc += "\n\n---\nGenerated by AI"
        else:
            pr_desc = "Generated by AI"
    result["pr_description"] = pr_desc

    # Extract security notes
    if "security notes" in sections:
        result["security_notes"] = _extract_bullet_points(sections["security notes"])

    # Extract dependencies
    if "dependencies" in sections:
        result["dependencies"] = _extract_bullet_points(sections["dependencies"])

    # Extract next steps
    if "next steps" in sections:
        result["next_steps"] = _extract_bullet_points(sections["next steps"])

    return result


def _split_into_sections(text: str) -> Dict[str, str]:
    """Split the output text into sections based on headers.

    Args:
        text: The text to split

    Returns:
        Dictionary mapping section names to content
    """
    sections = {}
    current_section = None
    current_content = []

    for line in text.split("\n"):
        # Check for section headers (## Header only, not ###)
        if line.startswith("##") and not line.startswith("###"):
            # Save previous section
            if current_section:
                sections[current_section] = "\n".join(current_content)

            # Start new section
            current_section = line.lstrip("#").strip().lower()
            current_content = []
        else:
            # Add to current section (including ### subsections)
            if current_section:
                current_content.append(line)

    # Save last section
    if current_section:
        sections[current_section] = "\n".join(current_content)

    return sections


def _extract_code_files(section_text: str) -> List[Dict[str, str]]:
    """Extract code files from a section.

    Looks for file path indicators and code blocks, extracting both.

    Args:
        section_text: Section text containing code files

    Returns:
        List of dictionaries with file information:
            [{"path": str, "content": str, "description": str}]
    """
    files = []
    lines = section_text.split("\n")
    current_file = None
    current_description = ""
    current_code = []
    in_code_block = False

    for line in lines:
        # Check for file path indicators (### filename.go or **File:** path)
        if line.strip().startswith("###") and ".go" in line:
            # Save previous file if exists
            if current_file and current_code:
                files.append({
                    "path": current_file,
                    "content": "\n".join(current_code),
                    "description": current_description
                })

            # Extract file path from header
            current_file = _extract_file_path(line)
            current_description = ""
            current_code = []
            in_code_block = False

        elif "**File:**" in line or "**Path:**" in line:
            # Save previous file if exists
            if current_file and current_code:
                files.append({
                    "path": current_file,
                    "content": "\n".join(current_code),
                    "description": current_description
                })

            # Extract file path
            current_file = _extract_file_path(line)
            current_description = ""
            current_code = []
            in_code_block = False

        # Handle code blocks
        elif line.strip().startswith("```"):
            if in_code_block:
                # End of code block
                in_code_block = False
            else:
                # Start of code block
                in_code_block = True
        elif in_code_block:
            current_code.append(line)
        elif current_file and not in_code_block and line.strip():
            # Collect description before code block
            if not current_code:
                current_description += line + "\n"

    # Save last file
    if current_file and current_code:
        files.append({
            "path": current_file,
            "content": "\n".join(current_code),
            "description": current_description
        })

    # If no specific files found, try to extract any Go code blocks
    if not files:
        go_code = _extract_first_code_block(section_text, "go")
        if go_code:
            files.append({
                "path": "generated_code.go",
                "content": go_code,
                "description": "Generated code file"
            })

    return files


def _extract_file_path(text: str) -> str:
    """Extract file path from various formats.

    Args:
        text: Text containing file path

    Returns:
        Extracted file path or generated name
    """
    # Remove markdown formatting
    text = text.strip("#").strip("*").strip()

    # Common patterns:
    # 1. "pkg/apis/build/v1beta1/timeout.go"
    # 2. "File: pkg/controller/buildrun_controller.go"
    # 3. "Path: `pkg/util/validation.go`"

    # Remove "File:" or "Path:" prefix
    text = re.sub(r'^(File|Path):\s*', '', text, flags=re.IGNORECASE)

    # Remove backticks
    text = text.strip("`")

    # Find .go file path
    match = re.search(r'[\w/\-\.]+\.go', text)
    if match:
        return match.group(0)

    # If no .go file found, return cleaned text
    return text.strip()


def _extract_first_code_block(text: str, language: Optional[str] = None) -> str:
    """Extract the first code block from markdown.

    Args:
        text: Text containing code blocks
        language: Optional language filter (go, yaml, etc.)

    Returns:
        Extracted code or empty string
    """
    in_code_block = False
    code_lines = []
    current_language = None

    for line in text.split("\n"):
        if line.strip().startswith("```"):
            if in_code_block:
                # End of code block
                if language is None or current_language == language:
                    break
                code_lines = []
                in_code_block = False
            else:
                # Start of code block
                in_code_block = True
                current_language = line.strip("`").strip() or None
                code_lines = []
        elif in_code_block:
            code_lines.append(line)

    return "\n".join(code_lines)


def _extract_bullet_points(text: str) -> List[str]:
    """Extract bullet points from text.

    Args:
        text: Text containing bullet points

    Returns:
        List of bullet point items
    """
    items = []

    for line in text.split("\n"):
        line = line.strip()
        # Match bullet points (-, *, •)
        if line.startswith("-") or line.startswith("*") or line.startswith("•"):
            item = line[1:].strip()
            if item:
                items.append(item)

    return items


def _build_review_feedback_section(context: Dict[str, Any]) -> str:
    """Build review feedback section for auto-fix iterations.

    Returns empty string on first iteration (no review yet).
    On subsequent iterations, formats findings as a mandatory fix list.
    This is the live implementation used by run_development; it is local to
    this module and not shared with config/agent_prompts.py.

    Args:
        context: AgentState dict, may contain review_findings and review_iteration.

    Returns:
        Formatted feedback block or empty string.
    """
    findings = context.get("review_findings", [])
    iteration = context.get("review_iteration", 0)

    if not findings or iteration == 0:
        return ""

    lines = [
        f"\n## ⚠️ Code Review Feedback (Iteration {iteration}) — MUST FIX",
        "The previous code generation had the following issues found during review.",
        "You MUST address ALL blocking issues in this new generation:\n",
    ]
    for finding in findings:
        lines.append(f"- {finding}")

    lines.append(
        "\nPay special attention to fixing blocking issues before proceeding.\n"
    )
    return "\n".join(lines)


def generate_file_summary(dev_results: Dict[str, Any]) -> str:
    """Generate a summary of code generation results.

    Args:
        dev_results: Results from run_development

    Returns:
        Formatted summary string
    """
    summary_lines = [
        "# Code Generation Summary\n",
        f"\n## Files Generated\n",
    ]

    code_count = len(dev_results.get("code_files", []))
    test_count = len(dev_results.get("test_files", []))
    total_count = code_count + test_count

    summary_lines.append(f"- **Code Files:** {code_count}\n")
    summary_lines.append(f"- **Test Files:** {test_count}\n")
    summary_lines.append(f"- **Total:** {total_count} file(s)\n")

    # List code files
    if code_count > 0:
        summary_lines.append(f"\n### Code Files\n")
        for file_info in dev_results["code_files"]:
            summary_lines.append(f"- `{file_info['path']}`")
            if file_info.get("description"):
                summary_lines.append(f" - {file_info['description'].strip()}")
            summary_lines.append("\n")

    # List test files
    if test_count > 0:
        summary_lines.append(f"\n### Test Files\n")
        for file_info in dev_results["test_files"]:
            summary_lines.append(f"- `{file_info['path']}`\n")

    # Add security notes
    security_notes = dev_results.get("security_notes", [])
    if security_notes:
        summary_lines.append(f"\n## Security Considerations\n")
        for note in security_notes:
            summary_lines.append(f"- {note}\n")

    # Add dependencies
    dependencies = dev_results.get("dependencies", [])
    if dependencies:
        summary_lines.append(f"\n## Dependencies Added\n")
        for dep in dependencies:
            summary_lines.append(f"- {dep}\n")

    # Add next steps
    next_steps = dev_results.get("next_steps", [])
    if next_steps:
        summary_lines.append(f"\n## Next Steps\n")
        for step in next_steps:
            summary_lines.append(f"- {step}\n")

    return "".join(summary_lines)
